[package]
name = "sample_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = { version = "0.29.0", features = ["all-keys", "electrum"]}
clap = { version = "4.5.17", features = ["derive"] }
miniscript = "12.2.0"
