version: "3"

services:
  bitcoind:
    restart: always
    container_name: bitcoind
    image: romeujr/bitcoin-core:27.1
    command:
      - -rpcport=43782
      - -rpcbind=0.0.0.0:43782
      - -port=39388
      - -whitelist=0.0.0.0/0
      - -regtest=1
      - -rest
      - -rpcallowip=::/0
      - -rpcpassword=bar
      - -rpcuser=foo
      - -server
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0
        rpcauth=liquid:c8bf1a8961d97f224cb21224aaa8235d$$402f4a8907683d057b8c58a42940b6e54d1638322a42986ae28ebb844e603ae6
    expose:
      - "43782"
      - "39388"
    ports:
      - "43782:43782"
      - "39388:39388"
    volumes:
      - "./bitcoin_datadir:/home/bitcoin/.bitcoin/"
    healthcheck:
      test: curl --fail "http://foo@localhost:18443/rest/chaininfo.json" || exit 1
      interval: 2s
      retries: 100
      start_period: 2s
      timeout: 2s

